### PR TITLE
Get latest tag (not tag associated with latest commit)

### PR DESCRIPTION
**Pull request by bakoontz2**

### CODE REVIEW

**Comment by bakoontz2** [comment]
See #31.

**Comment by WyriHaximus** [comment]
@bakoontz2 Just merged #33 to make sure we're running the latest `actions/checkout` version which should provide the tags. Could you rebase those changes in?

**Comment by WyriHaximus** [comment]
Also just merged #34 which adds testing to ensure the outputs will output something and otherwise fail the pipeline.

**Comment by bakoontz2** [comment]
This is great, thanks!  So what do you need me to do?  (Sorry, don't work much with github PRs...)

**Comment by WyriHaximus** [comment]
> This is great, thanks! So what do you need me to do? (Sorry, don't work much with github PRs...)

Right so first add this repository as a remote:

```shell
git remote add upstream https://github.com/WyriHaximus/github-action-get-previous-tag.git
```

Then fetch from that remote: 

```shell
git fetch upstream 
```

And then rebase:

```shell
git rebase -i upstream/master
```

**Comment by WyriHaximus** [comment]
> Sorry, don't work much with github PRs...

Don't be, I gladly help out with any questions you might have 😃 .

**Comment by bakoontz2** [comment]
Ah, that makes sense.  Done.

**Comment by WyriHaximus** [comment]
Thanks! (Didn't fully work out as expected, but it should be fine once merged.) Any clue why the tests are failing, it seems it isn't picking up the tag it should pick up?

**Comment by bakoontz2** [comment]
It's not really clear what is going on here:  So the PR is running *my* CI tests?

At any rate, there were two issues:  (1) Tags aren't copied over to forked repos by default. I had to do a ```git fetch --tags upstream; git push --tags```.  This fixed the ```previoustag``` failure.  (2) There is no longer an error generated when there are no tags to be fetched.  Code now checks for empty return value for tags after checking for errors.

The CI tests are returning successfully now.

**Review by WyriHaximus — APPROVED** [review]

**Pull request merged**
