### PR TITLE
Add last tag's timestamp

### PR DESCRIPTION
**Pull request by dargmuesli**
For me it is useful to know at which time the last timestamp was created. I want other tasks to run only if the last tag was created a certain while ago.

### CODE REVIEW

**Review by WyriHaximus — APPROVED** [review]
Great addition, thanks 👍 .

**Comment by WyriHaximus** [comment]
P.S. Will tag v1 later today

**Comment by dargmuesli** [comment]
🙈

**Comment by dargmuesli** [comment]
Any chance to get this out soon? :)

**Comment by WyriHaximus** [comment]
> :see_no_evil:
:speak_no_evil:

**Comment by WyriHaximus** [comment]
> Any chance to get this out soon? :)

Yes on it right now :tada:

**Comment by WyriHaximus** [comment]
@dargmuesli done: [`1.0.0`](https://github.com/WyriHaximus/github-action-get-previous-tag/releases/tag/1.0.0)

**Comment by dargmuesli** [comment]
Amazing, thank you!
amazing

**Pull request merged**
